.TH upgrade-ses.sh 8 "June 2016" "upgrade-ses.sh" "SES Upgrade"

.SH NAME
upgrade-ses.sh \- SES Upgrade Utility

.SH SYNOPSIS
.BI "upgrade-ses.sh [" options "] "

.SH OPTIONS
.TP
.BI "-c \-\-config " filename
Load a specific Ceph configuration file. Default is /etc/ceph/ceph.conf
.TP
.BI "-n \-\-non-interactive"
Run in non-interactive mode. All upgrade operations will be executed with no
input from the user. Users should read all relevant licenses before running the
script with this option, because they will be auto-accepted.
.TP
.BI "-s \-\-skip-osd-parttype-check"
Skip the OSD partition type checks. Only skip this check if you are certain your
OSD journal and data partitions are of the correct type, or because this check
is gating an upgrade that you must complete regarldess of potential OSD health.
.TP
.BI "-h \-\-help"
Print usage message.

.SH COPYRIGHT
Copyright (C) 2016 SUSE LINUX Products GmbH, Nuernberg, Germany.
.SH BUGS
Please report bugs at <https://bugzilla.suse.com>
.SH AUTHORS
Karol Mroz
